### ISSUE TITLE
index out of range error when running `hccore paradigm`

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-proto#682]
i'm getting this when running `$ hccore paradigm` on my local:

```
Davids-MacBook-Pro:~ davidmeister$ hccore paradigm
panic: runtime error: index out of range

goroutine 1 [running]:
main.action_paradigm(0x1122e91)
	/Users/davidmeister/go/src/github.com/holochain/holochain-proto/cmd/hccore/hccore.go:153 +0x104
main.setupApp.func1(0xc420220160, 0xc42009eb00, 0xc420220160)
	/Users/davidmeister/go/src/github.com/holochain/holochain-proto/cmd/hccore/hccore.go:64 +0x22
github.com/urfave/cli.HandleAction(0x19d2a60, 0x1cb8698, 0xc420220160, 0x0, 0xc42009eb40)
	/Users/davidmeister/go/src/github.com/urfave/cli/app.go:501 +0xc8
github.com/urfave/cli.Command.Run(0x1b584c2, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1b85a15, 0x41, 0x0, ...)
	/Users/davidmeister/go/src/github.com/urfave/cli/command.go:165 +0x47d
github.com/urfave/cli.(*App).Run(0xc42021e000, 0xc42000c060, 0x2, 0x2, 0x0, 0x0)
	/Users/davidmeister/go/src/github.com/urfave/cli/app.go:259 +0x6e8
main.main()
	/Users/davidmeister/go/src/github.com/holochain/holochain-proto/cmd/hccore/hccore.go:164 +0x4f
```

**Comment by zippy** [comment]
hccore is something I've never used its original intent, I think (I didn't write it) was to be able to swap out versions of the commands during dev so you could be running current versions and not get yourself messed up.  I was thinking of removing it for now.

**Comment by thedavidmeister** [comment]
@zippy i found it immediately after writing in the README how to work without it...

deleting code is always good :)

**Comment by thedavidmeister** [comment]
@zippy  i'll put a PR up that drops hccore then

**Comment by thedavidmeister** [comment]
<img width="985" alt="screen shot 2018-04-29 at 11 24 05 pm" src="https://user-images.githubusercontent.com/629710/39407111-7e41c770-4c04-11e8-998d-ce4c3f5fa419.png">

^^ hccore not existing in docker
